In [27]:
# anaconda installation with python 3.6 and 
# OpenCV from https://anaconda.org/conda-forge/opencv
# this program is run in Windows 10 on Jupyter notebook

# here we will dectect and count face in an image using OpenCV and Python.

# Source of reference -

# https://docs.opencv.org/3.0-beta/modules/objdetect/doc/cascade_classification.html?highlight=detectmultiscale#cv2.CascadeClassifier.detectMultiScale
# https://docs.opencv.org/3.0-beta/modules/imgproc/doc/drawing_functions.html?highlight=rectangle#puttext

# https://s.ndtvimg.com/images/content/2016/jan/806/team-india-3101.jpg


In [28]:
# Image  TeamIndia.JPG  has 25 faces 
# however the algorithm detects 21 faces correctly 
# with 1 incorrect face and missed 4 faces

In [29]:
import numpy as np
import cv2

#
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
# load image  
image = cv2.imread('TeamIndia.JPG')
# convert image to grayscale
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# here we return the detected faces in numpy ndarray
faces = face_cascade.detectMultiScale(grayImage)
# here we will have n rows (number of faces detected) 
# with 4 column that is rectangle 
print(type(faces))
# number of faces x 4(rectangle)
print(faces)
# number of faces detected
print(faces.shape)
print("Number of faces detected: " + str(faces.shape[0]))

# drawing green color rectangle in the original image 
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)

# display the image  
cv2.imshow('TeamFaces',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[393 302  55  55]
 [613 298  59  59]
 [405 175  55  55]
 [664 180  55  55]
 [290 180  67  67]
 [445  46  54  54]
 [176 188  62  62]
 [574  64  54  54]
 [231 351  61  61]
 [  6 234  58  58]
 [ 79  73  50  50]
 [ 75 280  60  60]
 [  3  77  54  54]
 [241  81  58  58]
 [153  83  55  55]
 [464  79  61  61]
 [755 292  51  51]
 [511 291  58  58]
 [179 282  61  61]
 [673 108  59  59]
 [ 87 135  58  58]
 [358 152  52  52]]
(22, 4)
Number of faces detected: 22
